name = "foundfootage-server"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
SOURCES_URL = ""
CONTACT_EMAIL = ""
CLIENT_VERSION = "0.4.2 (0.4.1-compatible; 0.4.0-compatible; 0.3.1-compatible; 0.3.0-compatible; 0.2.2-compatible; 0.2.1-compatible; 0.2.0-compatible; 0.1.0-compatible)"
R2_SIGNING = { ACCESS_KEY_ID = "", SECRET_ACCESS_KEY = "", CLOUDFLARE_ACCOUNT = "", BUCKET = "" }
# LOKI = { URL = "", AUTH = "" }
CLOUDFLARE_AUTH = { EMAIL = "", KEY = "" }

[vars.RATELIMITS]
ACCESS = { TIMEFRAME = "", THRESHOLD = "", BAN_THRESHOLD = "" }
NO_ROUTE = { TIMEFRAME = "", THRESHOLD = "", BAN_THRESHOLD = "" }

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""

[[r2_buckets]]
binding = "STORAGE"
bucket_name = ""
