name = "foundfootage-server"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
SOURCES_URL = ""
CONTACT_EMAIL = ""
CLIENT_VERSION = "0.2.0 (0.1.0-compatible)"

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""

[[r2_buckets]]
binding = "STORAGE"
bucket_name = ""
